version: "3.8"
services:

  # PHP Service
  php:
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
    depends_on:
      - db

  # Database Server
  db:
    image: mysql:8.0
    ports:
      - 33006:3306
    environment:
      - MYSQL_DATABASE=innoscripta_database
      - MYSQL_USER=innoscripta
      - MYSQL_PASSWORD=toor
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: ~
